[package]
name = "bmp180-driver"
version = "0.1.0"
authors = ["Rafael Milewski <rafael.milewski@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.71"

[dependencies]
embedded-hal = "1.0.0"
